namespace Titan.DataProvider.Domain.Models.GalaxyOfHeroes.GameData
{
    public enum OmicronMode
    {
        ALLOMICRON = 1,
        PVEOMICRON = 2,
        PVPOMICRON = 3,
        GUILDRAIDOMICRON = 4,
        TERRITORYSTRIKEOMICRON = 5,
        TERRITORYCOVERTOMICRON = 6,
        TERRITORYBATTLEBOTHOMICRON = 7,
        TERRITORYWAROMICRON = 8,
        TERRITORYTOURNAMENTOMICRON = 9,
        WAROMICRON = 10,
        CONQUESTOMICRON = 11,
        GALACTICCHALLENGEOMICRON = 12,
        PVEEVENTOMICRON = 13,
        TERRITORYTOURNAMENT3OMICRON = 14,
        TERRITORYTOURNAMENT5OMICRON = 15,
        GALACTICCHALLENGE3OMICRON = 16,
        GALACTICCHALLENGE5OMICRON = 17,
    }
}
